import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: {
        absolute:"Register"
    },
    description: "Generated by Register",
  };

function Register() {
  return (
    <div>Register</div>
  )
}

export default Register