import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: {
        absolute: "ForgetPassword"
    },
    description: "Generated by ForgetPassword",
};

function ForgetPassword() {
    return (
        <div>ForgetPassword</div>
    )
}

export default ForgetPassword