import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: {
        absolute: "Login"
    },
    description: "Generated by Login",
};

function Login() {
    return (
        <div>Login</div>
    )
}

export default Login